# Generated by Django 4.2.1 on 2024-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
