# Generated by Django 4.2.1 on 2024-05-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0002_userproducts_completed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_product_files/')),
            ],
        ),
        migrations.AddField(
            model_name='userproducts',
            name='files',
            field=models.ManyToManyField(blank=True, to='adminview.uploadedfile'),
        ),
    ]
