# Generated by Django 4.2.1 on 2024-05-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0003_uploadedfile_userproducts_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='completed_final_file',
            field=models.FileField(blank=True, null=True, upload_to='user_product_files/'),
        ),
    ]
