# Generated by Django 4.2.1 on 2024-05-21 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0004_userproducts_completed_final_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='completed_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 5, 21, 14, 52, 23, 666291, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
