# Generated by Django 4.2.1 on 2024-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0005_alter_userproducts_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='completed_on',
            field=models.DateTimeField(),
        ),
    ]
